/**:
  ros__parameters:
    # motion state constraints
    stop_decel: 0.0         # deceleration at a stop point[m/ss]

    # external velocity limit parameter
    margin_to_insert_external_velocity_limit: 0.3   #  margin distance to insert external velocity limit [m]

    # -- curve parameters  --
    # common parameters
    curvature_calculation_distance: 5.0
    # lateral acceleration limit parameters
    enable_lateral_acc_limit: true     # To toggle the lateral acc filter on and off. You can switch it dynamically at runtime.
    lateral_acceleration_limits: [1.0, 1.0, 1.0, 1.0]             # max lateral acceleration limit [m/ss]
    min_curve_velocity: 0.50
    decel_distance_before_curve: 2.0
    decel_distance_after_curve: 2.0    # slow speed distance after a curve for lateral acceleration limit
    min_decel_for_lateral_acc_lim_filter: -2.5  # deceleration limit applied in the lateral acceleration filter to avoid sudden braking [m/ss]
    # steering angle rate limit parameters
    enable_steering_rate_limit: true         # To toggle the steer rate filter on and off. You can switch it dynamically at runtime.
    velocity_thresholds: [0.1, 0.3, 20.0, 30.0]           # velocity thresholds in mps for steering angle rate limits [m/s]
    steering_angle_rate_limits: [11.5, 11.5, 10.5, 3.5]  # steering angle rates in degree for each velocity range [deg/s]
    resample_ds: 0.1                         # distance between trajectory points [m]
    curvature_threshold: 0.02                # if curvature > curvature_threshold, steeringRateLimit is triggered [1/m]

    # engage & replan parameters
    replan_vel_deviation: 1.0
    engage_velocity: 0.27
    engage_acceleration: 0.1
    engage_exit_ratio: 0.95
    stop_dist_to_prohibit_engage: 0.3

    # stop velocity
    stopping_velocity: 0.4
    stopping_distance: 3.0

    # path extraction parameters
    extract_ahead_dist: 200.0         # forward trajectory distance used for planning [m]
    extract_behind_dist: 5.0          # backward trajectory distance used for planning [m]
    delta_yaw_threshold: 1.0472       # Allowed delta yaw between ego pose and trajectory pose [radian]

    # resampling parameters for optimization
    max_trajectory_length: 200.0        # max trajectory length for resampling [m]
    min_trajectory_length: 180.0        # min trajectory length for resampling [m]
    resample_time: 2.0                  # resample total time for dense sampling [s]
    dense_resample_dt: 0.2              # resample time interval for dense sampling [s]
    dense_min_interval_distance: 0.1    # minimum points-interval length for dense sampling [m]
    sparse_resample_dt: 0.5             # resample time interval for sparse sampling [s]
    sparse_min_interval_distance: 4.0   # minimum points-interval length for sparse sampling [m]

    # resampling parameters for post process
    post_max_trajectory_length: 300.0        # max trajectory length for resampling [m]
    post_min_trajectory_length: 30.0         # min trajectory length for resampling [m]
    post_resample_time: 10.0                 # resample total time for dense sampling [s]
    post_dense_resample_dt: 0.1              # resample time interval for dense sampling [s]
    post_dense_min_interval_distance: 0.1    # minimum points-interval length for dense sampling [m]
    post_sparse_resample_dt: 0.1             # resample time interval for sparse sampling [s]
    post_sparse_min_interval_distance: 1.0   # minimum points-interval length for sparse sampling [m]

    # system
    over_stop_velocity_warn_thr: 1.389       # used to check if the optimization exceeds the input velocity on the stop point

    plan_from_ego_speed_on_manual_mode: true  # planning is done from ego velocity/acceleration on MANUAL mode. This should be true for smooth transition from MANUAL to AUTONOMOUS, but could be false for debugging.
